### ISSUE TITLE
Rename repository to arquillian.org

### ISSUE THREAD

**Issue by mojavelinux** [arquillian/arquillian.org#266]
Rename the repository to arquillian.org to better communicate its purpose (and since the .github.com domain for custom domains is deprecated).

**Comment by bartoszmajsak** [comment]
Shall we do it then?

**Comment by mojavelinux** [comment]
This is incredibly safe now that GitHub lets you control the GitHub Pages branch. You could continue to use the master branch regardless of the name of the repository.

**Comment by bartoszmajsak** [comment]
Done :) And happy birthday @mojavelinux ! You are missed!

**Comment by bartoszmajsak** [comment]
Turned out we cannot do that, because then redirect does not work for e.g. http://arquillian.org/arquillian-cube where we have all the docs. Renaming to .io as this is now the domain used for `gh-pages`
